In [1]:
#load libraries
import os
import io
import pandas as pd
import datetime as dt
import msoffcrypto
import openpyxl
import tkinter as tk
from tkinter import filedialog

In [ ]:
#set up function to select directory and list files in it

def select_directory():
    root = tk.Tk()
    root.withdraw() #hide the root window
    root.attributes('-topmost', True)

    try:
        cwd = filedialog.askdirectory(parent=root, title="Select a Folder")

        if cwd:
            cwd = cwd + "/"
            files = os.listdir(cwd)

            print(f"Selected folder: {cwd}")
            print("Files:", files)

            return cwd, files
        else:
            print("No folder selected.")
            return None, None

    finally:
        root.destroy() #always destroy the hidden root window


if __name__ == "__main__":
    cwd, files = select_directory()

In [3]:
#display files in current working directory, as a quick visual check
files

['.git',
 'File1.xlsx',
 'File2.xlsx',
 'File3.xlsx',
 'File_Aggregator.ipynb',
 'LICENSE',
 'README.md']

In [4]:
#count of Excel files
count = 0

for file in files:
    if file.endswith('.xlsx'):
        count = count + 1
print(count)

3

In [5]:
###**********THIS IS FOR NON-PASSWORD PROTECTED EXCEL FILES**********###

#combines all non-protected files, selecting only the 'Input Information' tab(s)
frames = []
for file in files:
    if file.endswith('.xlsx'):
        path = os.path.join(cwd, file)
        frames.append(pd.read_excel(path, sheet_name='Input Information'))
combined_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
combined_df.head()

     Project       Date    Status
0  Project 1 2020-04-05  Approved
1  Project 2 2020-04-06  Approved
2  Project 3 2020-04-07  Approved
3  Project 4 2020-04-08  Approved
4  Project 5 2020-04-09  Approved

In [13]:
###**********THIS IS FOR PASSWORD PROTECTED EXCEL FILES**********###

#combine all protected files, selecting only the 'Input Information' tab(s)
workbook = pd.DataFrame()
combined_df = pd.DataFrame()

start = dt.datetime.now()

for file in files:
    decrypted_workbook = io.BytesIO()
    workbook = pd.DataFrame()
    if file.endswith('.xlsx'):
        with open(cwd+file, 'rb') as data:
            office_file = msoffcrypto.OfficeFile(data)
            office_file.load_key(password='thisisthepassword') #PASSWORD goes here
            office_file.decrypt(decrypted_workbook)
            workbook = pd.read_excel(decrypted_workbook, sheet_name=2) #reference sheet 2 in workbook, not by sheet name. original value was "Input Information"
            combined_df = pd.concat([combined_df, workbook], ignore_index=True)

end = dt.datetime.now()

print(f'Elapsed Time: {end-start}')

DecryptionError: Document is not encrypted

In [6]:
#display combined data
combined_df

         Project       Date    Status
0      Project 1 2020-04-05  Approved
1      Project 2 2020-04-06  Approved
2      Project 3 2020-04-07  Approved
3      Project 4 2020-04-08  Approved
4      Project 5 2020-04-09  Approved
5      Project 6 2020-04-10  Approved
6      Project 7 2020-04-11  Approved
7      Project 8 2020-04-12  Approved
8      Project 9 2020-04-13  Approved
9     Project 10 2020-04-14  Approved
10    Project 11 2020-04-15  Approved
11    Project 12 2020-04-16  Approved
12    Project 13 2020-04-17  Rejected
13    Project 14 2020-04-18  Rejected
14    Project 15 2020-04-19  Rejected
15    Project 16 2020-04-20  Rejected
16    Project 17 2020-04-21  Rejected
17    Project 18 2020-04-22  Rejected
18    Project 19 2020-04-23  Rejected
19    Project 20 2020-04-24  Rejected
20    Project AA 2020-04-05  Approved
21    Project AA 2020-04-06  Approved
22    Project AA 2020-04-07  Approved
23    Project AA 2020-04-08  Approved
24    Project AA 2020-04-09  Approved
25    Project AA 2020-04-10  Approved
26    Project AA 2020-04-11  Approved
27    Project AA 2020-04-12  Approved
28    Project AA 2020-04-13  Approved
29    Project AA 2020-04-14  Approved
30  Project 1234 2020-04-15  Approved
31  Project 1235 2020-04-16  Approved
32  Project 1236 2020-04-17  Rejected
33  Project 1237 2020-04-18  Rejected
34  Project 1238 2020-04-19  Rejected
35  Project 1239 2020-04-20  Rejected
36  Project 1240 2020-04-21  Rejected
37  Project 1241 2020-04-22  Rejected
38  Project 1242 2020-04-23  Rejected
39  Project 1243 2020-04-24  Rejected
40     Project X 2028-04-05   Pending
41     Project X 2028-04-06   Pending
42     Project X 2028-04-07   Pending
43     Project X 2028-04-08   Pending
44     Project X 2028-04-09   Pending
45     Project X 2028-04-10   Pending
46     Project X 2028-04-11   Pending
47     Project X 2028-04-12   Pending
48     Project X 2028-04-13   Pending
49     Project X 2028-04-14   Pending
50     Project X 2028-04-15   Pending
51     Project X 2028-04-16   Pending
52     Project X 2028-04-17   Pending
53     Project X 2028-04-18   Pending
54     Project X 2028-04-19   Pending
55     Project X 2028-04-20   Pending
56     Project X 2028-04-21   Pending
57     Project X 2028-04-22   Pending
58     Project Y 2028-04-23   Pending
59     Project Y 2028-04-24   Pending

In [7]:
#clean up combined_df, null values
combined_df.dropna(thresh=2, inplace=True) #require 2 data points in the row to be kept, any less than 2 means the row is dropped

#any true NaNs filled as [blank]
combined_df.fillna("", inplace=True)

In [8]:
#display clean combined data for all files
combined_df

         Project       Date    Status
0      Project 1 2020-04-05  Approved
1      Project 2 2020-04-06  Approved
2      Project 3 2020-04-07  Approved
3      Project 4 2020-04-08  Approved
4      Project 5 2020-04-09  Approved
5      Project 6 2020-04-10  Approved
6      Project 7 2020-04-11  Approved
7      Project 8 2020-04-12  Approved
8      Project 9 2020-04-13  Approved
9     Project 10 2020-04-14  Approved
10    Project 11 2020-04-15  Approved
11    Project 12 2020-04-16  Approved
12    Project 13 2020-04-17  Rejected
13    Project 14 2020-04-18  Rejected
14    Project 15 2020-04-19  Rejected
15    Project 16 2020-04-20  Rejected
16    Project 17 2020-04-21  Rejected
17    Project 18 2020-04-22  Rejected
18    Project 19 2020-04-23  Rejected
19    Project 20 2020-04-24  Rejected
20    Project AA 2020-04-05  Approved
21    Project AA 2020-04-06  Approved
22    Project AA 2020-04-07  Approved
23    Project AA 2020-04-08  Approved
24    Project AA 2020-04-09  Approved
25    Project AA 2020-04-10  Approved
26    Project AA 2020-04-11  Approved
27    Project AA 2020-04-12  Approved
28    Project AA 2020-04-13  Approved
29    Project AA 2020-04-14  Approved
30  Project 1234 2020-04-15  Approved
31  Project 1235 2020-04-16  Approved
32  Project 1236 2020-04-17  Rejected
33  Project 1237 2020-04-18  Rejected
34  Project 1238 2020-04-19  Rejected
35  Project 1239 2020-04-20  Rejected
36  Project 1240 2020-04-21  Rejected
37  Project 1241 2020-04-22  Rejected
38  Project 1242 2020-04-23  Rejected
39  Project 1243 2020-04-24  Rejected
40     Project X 2028-04-05   Pending
41     Project X 2028-04-06   Pending
42     Project X 2028-04-07   Pending
43     Project X 2028-04-08   Pending
44     Project X 2028-04-09   Pending
45     Project X 2028-04-10   Pending
46     Project X 2028-04-11   Pending
47     Project X 2028-04-12   Pending
48     Project X 2028-04-13   Pending
49     Project X 2028-04-14   Pending
50     Project X 2028-04-15   Pending
51     Project X 2028-04-16   Pending
52     Project X 2028-04-17   Pending
53     Project X 2028-04-18   Pending
54     Project X 2028-04-19   Pending
55     Project X 2028-04-20   Pending
56     Project X 2028-04-21   Pending
57     Project X 2028-04-22   Pending
58     Project Y 2028-04-23   Pending
59     Project Y 2028-04-24   Pending

In [9]:
#create new output file with combined data and save to current working directory
combined_df.to_excel(cwd+'Aggregation_Output.xlsx')